title: Muhammad Haseeb Abid Awan
logo: images/profile-pic (7).png
description: |
  Experienced AI Engineer with expertise in Machine Learning, Deep Learning, CNNs, and AI/ML development.  
  Contact:  
  - 📧 Email: m.haseebabidawan@gmail.com  
  - 📱 WhatsApp: +923045662002
show_downloads: true
theme: jekyll-theme-minimal
